# MockMach -- sounds like mäk mäk (which rhymes with what a chiken would say)
title: "MockMach"

# current version
version: "0.3.0"

# replace with the mockups main email address
email: hi@dereknutile.com

# brief description for the site
description: "MockMach is a light framework that can be used to easily create website mock-ups for clients."

# one line short description for the site
tagline: "The Mock-up Machine"

# leave empty unless you need to store the mockup in a subfolder
# don't use a trailing slash
baseurl: ""

# replace with the domain of the mockup
url: "http://mockmach.com/"
repo: "https://github.com/MockMach/mockmach.github.io"
zipfile: "https://github.com/MockMach/mockmach/archive/master.zip"

# site favicon
favicon: "/assets/ico/favicon.png"

# usernames
facebook-username: "mockmach"
twitter-username: "mockmach"
gootgle-plus-username: "+mockmach"

# analytic settings
google-analytics: "UA-55205759-1"

# Jekyll build settings
markdown: kramdown
permalink: pretty
